#!/usr/bin/env bash
set -Eeuo pipefail

usage() {
  cat <<'EOF'
Usage:
  bash ops/public/import-public-image-bundle.sh \
    --release <40-character-git-sha> \
    --target-directory <bundle-directory> \
    [--backend-image vibelo-public-backend:<git-sha>] \
    [--frontend-image vibelo-public-frontend:<git-sha>] \
    [--validate-only]

The target directory must contain exactly the release bundle, image manifest,
and SHA256SUMS generated by Export-PublicImageBundle.ps1.

--validate-only verifies the complete offline package without loading images.
Successful validation/import emits the validated fixed MinIO image content ID as
VIBELO_MINIO_IMAGE_ID for the release controller's pre-load runtime identity gate.
EOF
}

die() {
  printf 'ERROR: %s\n' "$*" >&2
  exit 1
}

RELEASE=''
TARGET_DIRECTORY=''
BACKEND_IMAGE=''
FRONTEND_IMAGE=''
DOCKER_COMMAND=docker
PYTHON_COMMAND=python3
VALIDATE_ONLY=false

while (($#)); do
  case "$1" in
    --release)
      (($# >= 2)) || die '--release requires a value'
      RELEASE=$2
      shift 2
      ;;
    --target-directory)
      (($# >= 2)) || die '--target-directory requires a value'
      TARGET_DIRECTORY=$2
      shift 2
      ;;
    --backend-image)
      (($# >= 2)) || die '--backend-image requires a value'
      BACKEND_IMAGE=$2
      shift 2
      ;;
    --frontend-image)
      (($# >= 2)) || die '--frontend-image requires a value'
      FRONTEND_IMAGE=$2
      shift 2
      ;;
    --docker-command)
      (($# >= 2)) || die '--docker-command requires a value'
      DOCKER_COMMAND=$2
      shift 2
      ;;
    --python-command)
      (($# >= 2)) || die '--python-command requires a value'
      PYTHON_COMMAND=$2
      shift 2
      ;;
    --validate-only)
      VALIDATE_ONLY=true
      shift
      ;;
    -h | --help)
      usage
      exit 0
      ;;
    *)
      die "unknown argument: $1"
      ;;
  esac
done

[[ $RELEASE =~ ^[0-9a-fA-F]{40}$ ]] || die '--release must be a full 40-character Git SHA'
RELEASE=${RELEASE,,}
[[ -n $TARGET_DIRECTORY ]] || die '--target-directory is required'
[[ -n $BACKEND_IMAGE ]] || BACKEND_IMAGE="vibelo-public-backend:$RELEASE"
[[ -n $FRONTEND_IMAGE ]] || FRONTEND_IMAGE="vibelo-public-frontend:$RELEASE"

validate_release_ref() {
  local ref=$1
  local label=$2

  [[ -n $ref &&
    $ref != *[[:space:]]* &&
    $ref != *@* &&
    $ref == *":$RELEASE" ]] ||
    die "$label must be an explicit image tag ending in :$RELEASE"
}

validate_release_ref "$BACKEND_IMAGE" BackendImage
validate_release_ref "$FRONTEND_IMAGE" FrontendImage
[[ $BACKEND_IMAGE != "$FRONTEND_IMAGE" ]] || die 'backend and frontend image tags must be different'

command -v sha256sum >/dev/null 2>&1 || die 'sha256sum is required'
command -v "$PYTHON_COMMAND" >/dev/null 2>&1 || die "Python command is unavailable: $PYTHON_COMMAND"
command -v "$DOCKER_COMMAND" >/dev/null 2>&1 || die "Docker command is unavailable: $DOCKER_COMMAND"

[[ -d $TARGET_DIRECTORY && ! -L $TARGET_DIRECTORY ]] ||
  die 'target directory must exist and must not be a symlink'
TARGET_DIRECTORY=$(cd -- "$TARGET_DIRECTORY" && pwd -P)

BUNDLE_NAME="vibelo-public-$RELEASE-linux-amd64.tar"
MANIFEST_NAME="vibelo-public-$RELEASE-images.tsv"
BUNDLE_PATH=$TARGET_DIRECTORY/$BUNDLE_NAME
MANIFEST_PATH=$TARGET_DIRECTORY/$MANIFEST_NAME
CHECKSUMS_PATH=$TARGET_DIRECTORY/SHA256SUMS

mapfile -t package_entries < <(
  find -P "$TARGET_DIRECTORY" -mindepth 1 -maxdepth 1 -printf '%f\n' | LC_ALL=C sort
)
expected_entries=$(printf '%s\n' "$BUNDLE_NAME" "$MANIFEST_NAME" SHA256SUMS | LC_ALL=C sort)
actual_entries=$(printf '%s\n' "${package_entries[@]-}")
[[ $actual_entries == "$expected_entries" ]] ||
  die 'target directory must contain exactly bundle, manifest, and SHA256SUMS'

for required_file in "$BUNDLE_PATH" "$MANIFEST_PATH" "$CHECKSUMS_PATH"; do
  [[ -f $required_file && ! -L $required_file ]] ||
    die "required package file is missing or unsafe: $(basename -- "$required_file")"
done
[[ -s $BUNDLE_PATH && -s $MANIFEST_PATH && -s $CHECKSUMS_PATH ]] ||
  die 'release package files must not be empty'

mapfile -t checksum_lines <"$CHECKSUMS_PATH"
((${#checksum_lines[@]} == 2)) || die 'SHA256SUMS must contain exactly two records'
[[ ${checksum_lines[0]} =~ ^([0-9a-f]{64})[[:space:]][[:space:]]([^/]+)$ ]] ||
  die 'invalid bundle checksum record'
expected_bundle_sha=${BASH_REMATCH[1]}
bundle_checksum_name=${BASH_REMATCH[2]}
[[ $bundle_checksum_name == "$BUNDLE_NAME" ]] || die 'bundle checksum filename mismatch'
[[ ${checksum_lines[1]} =~ ^([0-9a-f]{64})[[:space:]][[:space:]]([^/]+)$ ]] ||
  die 'invalid manifest checksum record'
expected_manifest_sha=${BASH_REMATCH[1]}
manifest_checksum_name=${BASH_REMATCH[2]}
[[ $manifest_checksum_name == "$MANIFEST_NAME" ]] || die 'manifest checksum filename mismatch'

actual_bundle_sha=$(sha256sum "$BUNDLE_PATH" | awk '{print $1}')
actual_manifest_sha=$(sha256sum "$MANIFEST_PATH" | awk '{print $1}')
[[ $actual_bundle_sha == "$expected_bundle_sha" ]] || die 'bundle SHA256 mismatch'
[[ $actual_manifest_sha == "$expected_manifest_sha" ]] || die 'manifest SHA256 mismatch'

expected_refs=(
  'nginx:1.27-alpine'
  "$FRONTEND_IMAGE"
  "$BACKEND_IMAGE"
  'redis:7.4-alpine'
  'docker.elastic.co/elasticsearch/elasticsearch:8.14.3'
  'confluentinc/cp-zookeeper:7.6.1'
  'confluentinc/cp-kafka:7.6.1'
  'minio/minio:RELEASE.2025-04-22T22-12-26Z'
)

mapfile -t manifest_lines <"$MANIFEST_PATH"
((${#manifest_lines[@]} == 9)) || die 'manifest must contain one header and exactly eight images'
[[ ${manifest_lines[0]} == $'ref\timage_id\tos\tarch' ]] || die 'manifest header is invalid'

declare -a expected_ref_id_lines=()
for index in "${!expected_refs[@]}"; do
  line=${manifest_lines[index + 1]}
  tab_characters=${line//[^$'\t']/}
  ((${#tab_characters} == 3)) || die "manifest row has an invalid column count: $((index + 2))"
  IFS=$'\t' read -r ref image_id os arch <<<"$line"
  [[ $ref == "${expected_refs[index]}" ]] ||
    die "manifest has an extra, missing, or out-of-order image at row $((index + 2))"
  [[ $image_id =~ ^sha256:[0-9a-f]{64}$ ]] || die "manifest image ID is invalid: $ref"
  [[ $os == linux && $arch == amd64 ]] || die "manifest image is not linux/amd64: $ref"
  expected_ref_id_lines+=("$ref"$'\t'"$image_id")
done

ARCHIVE_RECORDS=$(mktemp)
trap 'rm -f -- "$ARCHIVE_RECORDS"' EXIT
"$PYTHON_COMMAND" - \
  "$BUNDLE_PATH" \
  "$RELEASE" \
  "$BACKEND_IMAGE" \
  "$FRONTEND_IMAGE" >"$ARCHIVE_RECORDS" <<'PY'
import json
import hashlib
import pathlib
import re
import sys
import tarfile

bundle = pathlib.Path(sys.argv[1])
release = sys.argv[2]
application_images = {sys.argv[3], sys.argv[4]}


def read_member(archive, name, label):
    try:
        member = archive.getmember(name)
    except KeyError as exc:
        raise SystemExit(f"bundle {label} is missing") from exc
    if not member.isfile():
        raise SystemExit(f"bundle {label} is not a regular file")
    stream = archive.extractfile(member)
    if stream is None:
        raise SystemExit(f"bundle {label} cannot be read")
    return member, stream.read()


def read_json_member(archive, name, label):
    _, raw = read_member(archive, name, label)
    try:
        return json.loads(raw)
    except (UnicodeDecodeError, json.JSONDecodeError) as exc:
        raise SystemExit(f"bundle {label} is not valid JSON") from exc


def read_digest_blob(archive, digest, label, expected_size=None):
    if not isinstance(digest, str) or not re.fullmatch(r"sha256:[0-9a-f]{64}", digest):
        raise SystemExit(f"bundle {label} digest is invalid")
    digest_hex = digest[7:]
    _, raw = read_member(archive, "blobs/sha256/" + digest_hex, label)
    if hashlib.sha256(raw).hexdigest() != digest_hex:
        raise SystemExit(f"bundle {label} digest mismatch")
    if expected_size is not None and expected_size != len(raw):
        raise SystemExit(f"bundle {label} size mismatch")
    return raw


def validate_application_revision(config_blob, image_ref):
    try:
        config_payload = json.loads(config_blob)
    except (UnicodeDecodeError, json.JSONDecodeError) as exc:
        raise SystemExit(f"bundle application image config is not valid JSON: {image_ref}") from exc
    runtime_config = config_payload.get("config") if isinstance(config_payload, dict) else None
    labels = runtime_config.get("Labels") if isinstance(runtime_config, dict) else None
    revision = (
        labels.get("org.opencontainers.image.revision")
        if isinstance(labels, dict)
        else None
    )
    if revision != release:
        raise SystemExit(f"bundle application image revision label mismatch: {image_ref}")


with tarfile.open(bundle, "r:*") as archive:
    payload = read_json_member(archive, "manifest.json", "manifest.json")
    if not isinstance(payload, list):
        raise SystemExit("bundle manifest.json must be an array")

    manifest_ref_by_config = {}
    for item in payload:
        if not isinstance(item, dict):
            raise SystemExit("bundle manifest entry must be an object")
        config = item.get("Config")
        tags = item.get("RepoTags")
        if not isinstance(config, str):
            raise SystemExit("bundle image config name is invalid")
        if not isinstance(tags, list) or len(tags) != 1 or not isinstance(tags[0], str):
            raise SystemExit("each bundle image must contain exactly one tagged reference")
        if config in manifest_ref_by_config:
            raise SystemExit("bundle image config is referenced by multiple tagged images")
        manifest_ref_by_config[config] = tags[0]

    try:
        archive.getmember("index.json")
    except KeyError:
        index_payload = None
    else:
        index_payload = read_json_member(archive, "index.json", "index.json")

    oci_descriptors_by_config = {}
    all_oci_descriptor_ids = set()
    validated_application_images = set()
    if index_payload is not None:
        if not isinstance(index_payload, dict) or not isinstance(index_payload.get("manifests"), list):
            raise SystemExit("bundle index.json is invalid")
        attestation_descriptors = []
        for descriptor in index_payload["manifests"]:
            if not isinstance(descriptor, dict):
                raise SystemExit("bundle index descriptor must be an object")
            digest = descriptor.get("digest")
            size = descriptor.get("size")
            if not isinstance(size, int) or isinstance(size, bool) or size < 0:
                raise SystemExit("bundle platform manifest size is invalid")
            annotations = descriptor.get("annotations")
            if "platform" not in descriptor:
                if (
                    descriptor.get("mediaType") != "application/vnd.oci.image.manifest.v1+json"
                    or not isinstance(annotations, dict)
                    or set(annotations) != {"io.containerd.manifest.subject"}
                    or not isinstance(annotations.get("io.containerd.manifest.subject"), str)
                ):
                    raise SystemExit("bundle index descriptor platform is invalid")
                attestation_descriptors.append(
                    ("containerd", digest, size, annotations["io.containerd.manifest.subject"])
                )
                continue
            platform = descriptor.get("platform")
            if not isinstance(platform, dict):
                raise SystemExit("bundle index descriptor platform is invalid")
            if platform.get("os") == "unknown" and platform.get("architecture") == "unknown":
                if (
                    descriptor.get("mediaType") != "application/vnd.oci.image.manifest.v1+json"
                    or not isinstance(annotations, dict)
                    or annotations.get("vnd.docker.reference.type") != "attestation-manifest"
                    or not isinstance(annotations.get("vnd.docker.reference.digest"), str)
                ):
                    raise SystemExit("bundle index contains an unsupported non-runnable descriptor")
                attestation_descriptors.append(
                    ("docker", digest, size, annotations["vnd.docker.reference.digest"])
                )
                continue
            if platform.get("os") != "linux" or platform.get("architecture") != "amd64":
                raise SystemExit("bundle index contains a non-linux-amd64 image")
            if descriptor.get("mediaType") not in {
                "application/vnd.docker.distribution.manifest.v2+json",
                "application/vnd.oci.image.manifest.v1+json",
            }:
                raise SystemExit("bundle runnable manifest media type is invalid")
            blob = read_digest_blob(archive, digest, "platform manifest blob", size)
            try:
                platform_manifest = json.loads(blob)
            except (UnicodeDecodeError, json.JSONDecodeError) as exc:
                raise SystemExit("bundle platform manifest is not valid JSON") from exc
            config_descriptor = platform_manifest.get("config") if isinstance(platform_manifest, dict) else None
            config_digest = config_descriptor.get("digest") if isinstance(config_descriptor, dict) else None
            config_size = config_descriptor.get("size") if isinstance(config_descriptor, dict) else None
            if not isinstance(config_size, int) or isinstance(config_size, bool) or config_size < 0:
                raise SystemExit("bundle platform config size is invalid")
            config_blob = read_digest_blob(
                archive, config_digest, "platform config blob", config_size
            )
            config_name = "blobs/sha256/" + config_digest.removeprefix("sha256:")
            image_ref = manifest_ref_by_config.get(config_name)
            if image_ref in application_images:
                validate_application_revision(config_blob, image_ref)
                validated_application_images.add(image_ref)
            oci_descriptors_by_config.setdefault(config_digest, set()).add(digest)
            all_oci_descriptor_ids.add(digest)

        for attestation_kind, digest, size, target_digest in attestation_descriptors:
            if target_digest not in all_oci_descriptor_ids:
                raise SystemExit("bundle attestation does not reference a runnable image manifest")
            blob = read_digest_blob(archive, digest, "attestation manifest blob", size)
            try:
                attestation_manifest = json.loads(blob)
            except (UnicodeDecodeError, json.JSONDecodeError) as exc:
                raise SystemExit("bundle attestation manifest is not valid JSON") from exc
            if (
                not isinstance(attestation_manifest, dict)
                or attestation_manifest.get("schemaVersion") != 2
                or attestation_manifest.get("mediaType") != "application/vnd.oci.image.manifest.v1+json"
            ):
                raise SystemExit("bundle attestation manifest is invalid")
            artifact_type = attestation_manifest.get("artifactType")
            if (
                artifact_type is not None
                and artifact_type != "application/vnd.docker.attestation.manifest.v1+json"
            ):
                raise SystemExit("bundle attestation artifact type is invalid")
            subject = attestation_manifest.get("subject")
            if attestation_kind == "containerd":
                if artifact_type is not None or subject is not None:
                    raise SystemExit("bundle containerd attestation payload shape is invalid")
            else:
                if artifact_type is not None and not isinstance(subject, dict):
                    raise SystemExit("bundle OCI attestation subject is missing")
                if subject is not None:
                    if not isinstance(subject, dict) or subject.get("digest") != target_digest:
                        raise SystemExit("bundle attestation subject does not match its runnable image")
            config_descriptor = attestation_manifest.get("config")
            config_digest = config_descriptor.get("digest") if isinstance(config_descriptor, dict) else None
            config_size = config_descriptor.get("size") if isinstance(config_descriptor, dict) else None
            if not isinstance(config_size, int) or isinstance(config_size, bool) or config_size < 0:
                raise SystemExit("bundle attestation config size is invalid")
            config_blob = read_digest_blob(
                archive, config_digest, "attestation config blob", config_size
            )
            containerd_diff_ids = None
            if attestation_kind == "containerd":
                if config_descriptor.get("mediaType") != "application/vnd.oci.image.config.v1+json":
                    raise SystemExit("bundle containerd attestation config media type is invalid")
                try:
                    config_payload = json.loads(config_blob)
                except (UnicodeDecodeError, json.JSONDecodeError) as exc:
                    raise SystemExit("bundle containerd attestation config is not valid JSON") from exc
                rootfs = config_payload.get("rootfs") if isinstance(config_payload, dict) else None
                containerd_diff_ids = rootfs.get("diff_ids") if isinstance(rootfs, dict) else None
                if (
                    not isinstance(config_payload, dict)
                    or set(config_payload) != {"architecture", "config", "os", "rootfs"}
                    or config_payload.get("architecture") != "unknown"
                    or config_payload.get("os") != "unknown"
                    or config_payload.get("config") != {}
                    or not isinstance(rootfs, dict)
                    or set(rootfs) != {"diff_ids", "type"}
                    or rootfs.get("type") != "layers"
                    or not isinstance(containerd_diff_ids, list)
                    or not all(
                        isinstance(item, str) and re.fullmatch(r"sha256:[0-9a-f]{64}", item)
                        for item in containerd_diff_ids
                    )
                ):
                    raise SystemExit("bundle containerd attestation config shape is invalid")
            layers = attestation_manifest.get("layers")
            if not isinstance(layers, list) or not layers:
                raise SystemExit("bundle attestation layers are invalid")
            target_hex = target_digest.removeprefix("sha256:")
            layer_digests = []
            for layer in layers:
                if not isinstance(layer, dict) or layer.get("mediaType") != "application/vnd.in-toto+json":
                    raise SystemExit("bundle attestation layer media type is invalid")
                layer_size = layer.get("size")
                if not isinstance(layer_size, int) or isinstance(layer_size, bool) or layer_size < 0:
                    raise SystemExit("bundle attestation layer size is invalid")
                layer_blob = read_digest_blob(
                    archive, layer.get("digest"), "attestation layer blob", layer_size
                )
                layer_digests.append(layer["digest"])
                try:
                    statement = json.loads(layer_blob)
                except (UnicodeDecodeError, json.JSONDecodeError) as exc:
                    raise SystemExit("bundle in-toto attestation is not valid JSON") from exc
                subjects = statement.get("subject") if isinstance(statement, dict) else None
                if (
                    not isinstance(statement, dict)
                    or statement.get("_type")
                    not in {
                        "https://in-toto.io/Statement/v0.1",
                        "https://in-toto.io/Statement/v1",
                    }
                ):
                    raise SystemExit("bundle in-toto attestation statement type is invalid")
                if (
                    not isinstance(subjects, list)
                    or not subjects
                    or not all(
                        isinstance(item, dict)
                        and isinstance(item.get("digest"), dict)
                        and item["digest"].get("sha256") == target_hex
                        for item in subjects
                    )
                ):
                    raise SystemExit("bundle in-toto attestation subject does not match its runnable image")
                layer_annotations = layer.get("annotations")
                predicate_type = statement.get("predicateType") if isinstance(statement, dict) else None
                if (
                    attestation_kind == "containerd"
                    and (
                        not isinstance(layer_annotations, dict)
                        or not isinstance(layer_annotations.get("in-toto.io/predicate-type"), str)
                    )
                ):
                    raise SystemExit("bundle containerd attestation layer annotation is invalid")
                if (
                    isinstance(layer_annotations, dict)
                    and "in-toto.io/predicate-type" in layer_annotations
                    and layer_annotations["in-toto.io/predicate-type"] != predicate_type
                ):
                    raise SystemExit("bundle attestation predicate type annotation is inconsistent")
            if attestation_kind == "containerd" and containerd_diff_ids != layer_digests:
                raise SystemExit("bundle containerd attestation config does not match its layers")

    used_oci_descriptor_ids = set()
    for item in payload:
        if not isinstance(item, dict):
            raise SystemExit("bundle manifest entry must be an object")
        config = item.get("Config")
        tags = item.get("RepoTags")
        if not isinstance(config, str):
            raise SystemExit("bundle image config name is invalid")
        if not isinstance(tags, list) or len(tags) != 1 or not isinstance(tags[0], str):
            raise SystemExit("each bundle image must contain exactly one tagged reference")
        legacy_match = re.fullmatch(r"([0-9a-f]{64})\.json", config)
        oci_match = re.fullmatch(r"blobs/sha256/([0-9a-f]{64})", config)
        if legacy_match:
            config_hex = legacy_match.group(1)
            _, config_blob = read_member(archive, config, "legacy image config")
            if hashlib.sha256(config_blob).hexdigest() != config_hex:
                raise SystemExit("bundle legacy image config digest mismatch")
            if tags[0] in application_images:
                validate_application_revision(config_blob, tags[0])
                validated_application_images.add(tags[0])
            image_id = "sha256:" + config_hex
        elif oci_match:
            config_digest = "sha256:" + oci_match.group(1)
            platform_ids = oci_descriptors_by_config.get(config_digest, set())
            if len(platform_ids) != 1:
                raise SystemExit("bundle config does not map to exactly one linux/amd64 image manifest")
            image_id = next(iter(platform_ids))
            used_oci_descriptor_ids.add(image_id)
        else:
            raise SystemExit("bundle image config name is invalid")
        print(f"{tags[0]}\t{image_id}")

    if index_payload is not None and used_oci_descriptor_ids != all_oci_descriptor_ids:
        raise SystemExit("bundle index contains an extra or missing image descriptor")
    if validated_application_images != application_images:
        raise SystemExit("bundle application image revision labels were not fully validated")
PY

mapfile -t archive_ref_id_lines <"$ARCHIVE_RECORDS"
((${#archive_ref_id_lines[@]} == 8)) || die 'bundle must contain exactly eight tagged images'
expected_sorted=$(printf '%s\n' "${expected_ref_id_lines[@]}" | LC_ALL=C sort)
archive_sorted=$(printf '%s\n' "${archive_ref_id_lines[@]}" | LC_ALL=C sort)
[[ $archive_sorted == "$expected_sorted" ]] ||
  die 'bundle images do not exactly match the signed TSV manifest'

MINIO_IMAGE_ID=''
for ref_id_line in "${expected_ref_id_lines[@]}"; do
  IFS=$'\t' read -r ref image_id <<<"$ref_id_line"
  if [[ $ref == 'minio/minio:RELEASE.2025-04-22T22-12-26Z' ]]; then
    MINIO_IMAGE_ID=$image_id
    break
  fi
done
[[ $MINIO_IMAGE_ID =~ ^sha256:[0-9a-f]{64}$ ]] || die 'validated MinIO image ID is missing'

if [[ $VALIDATE_ONLY == true ]]; then
  printf 'Public image bundle validation passed for release %s; no image was loaded.\n' "$RELEASE"
  printf 'VIBELO_BACKEND_IMAGE=%s\n' "$BACKEND_IMAGE"
  printf 'VIBELO_FRONTEND_IMAGE=%s\n' "$FRONTEND_IMAGE"
  printf 'VIBELO_MINIO_IMAGE_ID=%s\n' "$MINIO_IMAGE_ID"
  exit 0
fi

if ! load_output=$("$DOCKER_COMMAND" image load --input "$BUNDLE_PATH" 2>&1); then
  die "docker image load failed: $load_output"
fi

for index in "${!expected_refs[@]}"; do
  ref=${expected_refs[index]}
  IFS=$'\t' read -r _ expected_id _ _ <<<"${manifest_lines[index + 1]}"
  if ! inspect_output=$("$DOCKER_COMMAND" image inspect --platform linux/amd64 \
    --format '{{.Id}}|{{.Os}}|{{.Architecture}}' "$ref" 2>&1); then
    die "loaded image is missing: $ref"
  fi
  [[ $inspect_output != *$'\n'* ]] || die "loaded image inspection returned multiple rows: $ref"
  IFS='|' read -r actual_id actual_os actual_arch <<<"$inspect_output"
  actual_id=${actual_id,,}
  actual_os=${actual_os,,}
  actual_arch=${actual_arch,,}
  [[ $actual_id == "$expected_id" ]] || die "loaded image ID mismatch: $ref"
  [[ $actual_os == linux && $actual_arch == amd64 ]] || die "loaded image platform mismatch: $ref"
done

printf 'Public image bundle import verified for release %s.\n' "$RELEASE"
printf 'VIBELO_BACKEND_IMAGE=%s\n' "$BACKEND_IMAGE"
printf 'VIBELO_FRONTEND_IMAGE=%s\n' "$FRONTEND_IMAGE"
printf 'VIBELO_MINIO_IMAGE_ID=%s\n' "$MINIO_IMAGE_ID"
